### ISSUE TITLE
Scene Duplicate Issue

### ISSUE THREAD

**Issue by Sansar1234** [Teckiee/KnightLight#14]
When editing a duplicated scene the program edits all "duped" scenes as if they were all the same, this is fixed by refreshing/reloading the bank or restarting the program. If duplicating a scene with automation a restart is required to edit the scenes automation functions

**Comment by Teckiee** [comment]
Scene code is vastly changed. a few various duplication functions seem to be working well now. Need to test with actual lights to make sure values are as expected.

**Comment by Teckiee** [comment]
It wasn't fixed, but now it is!
