### ISSUE TITLE
Updating Time and Fade Cause Dupe scene

### ISSUE THREAD

**Issue by Sansar1234** [Teckiee/KnightLight#16]
Updating the timing for a scene change in song works fine, but if you want to change the fade it adds an extra scene with the fade and also without the fade changes
![image](https://user-images.githubusercontent.com/98821105/182185860-a01fc3ee-b289-499a-add8-a44b610be42a.png)
Here you can see I tried changing the time to 26.18 and removed the fade and it duplicated the scene

**Comment by Teckiee** [comment]
This was an annoying one because it doesn't do the bug when opened in VS debugging. I adjusted some things and tested it as working on the lighting pc though.
